apiVersion: v1
kind: Service
metadata:
  labels: null
  name: monitoring-influxdb
  namespace: kube-system
spec:
  clusterIP: 10.3.0.20
  ports:
  - port: 8086
    targetPort: 8086
  selector:
    name: influxGrafana