apiVersion: v1
kind: Service
metadata:
  labels: null
  name: influxdb-ui
  namespace: kube-system
spec:
  clusterIP: 10.3.0.30
  ports:
  - port: 8083
    targetPort: 8083
  selector:
    name: influxGrafana